SELECT *
FROM Employees
WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS);

SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_IDENT
FROM JOBS
Where JOB_IDENT IN (SELECT JOB_IDENT From EMPLOYEES WHERE SALARY > 70000);

SELECT * FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

SELECT * From JOBS;

SELECT EMP_ID, F_NAME, L_NAME, JOB_TITLE
EMPLOYEES E, JOBS J
WHERE E.JOB_ID = JOB_IDENT;