SELECT * 
FROM EMPLOYEES
WHERE salary < (SELECT AVG(SALARY) From EMPLOYEES);

SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) as MAX_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) 
FROM (SELECT SALARY
        FROM EMPLOYEES
        ORDER BY SALARY DESC
        LIMIT 5) AS SALARY_TABLE;