-- -- SQLite
-- SELECT * FROM DEPARTMENTS;
-- SELECT * FROM JOBS;
-- SELECT * FROM JOB_history;
-- SELECT * FROM Locations;
-- SELECT * FROM Employees;

SELECT F_NAME, L_NAME
FROM EMPLOYEES
WHERE ADDRESS LIKE '%Elgin,IL%';