-- -- SQLite
-- SELECT * FROM DEPARTMENTS;
-- SELECT * FROM JOBS;
-- SELECT * FROM JOB_history;
-- SELECT * FROM Locations;
-- SELECT * FROM Employees;

SELECT F_NAME, L_NAME, ADDRESS
FROM EMPLOYEES
WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT F_NAME, L_NAME, B_DATE FROM EMPLOYEES 
WHERE B_DATE LIKE '197%';

SELECT * FROM EMPLOYEES
WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID = 5;

-- Retrieve all employees ordered by dep_id
SELECT F_NAME, L_NAME, DEP_ID
FROM EMPLOYEES
ORDER BY DEP_ID;

-- Retrieve all employees ordered by dep_id backwards
SELECT F_NAME, L_NAME FROM EMPLOYEES
ORDER BY DEP_ID, L_NAME DESC;

